import { NextUIProvider } from '@nextui-org/react'
import './globals.css'

export const metadata = {
  title: 'Warsztat samochodowy',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        {/* <header className="bg-slate-900 text-white p-4 text-center">
          <p>System wewnętrzny</p>
        </header> */}
        {children}
      </body>
    </html>
  )
}
